version: "3.7"

services:
  splunk:
    build:
      dockerfile: ./docker/splunk/Dockerfile
      context: ./
      args:
        - DOCKER_IMAGE=$DOCKER_IMAGE
        - SPLUNK_VERSION=$SPLUNK_VERSION
    ports:
      - "8000" # Web UI
      - "8088" # HEC
      - "8089" # REST API
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Chang3d!
      - SPLUNK_HEC_TOKEN=abcd1234
    volumes:
      - "./output/TA-nextdns-api:/opt/splunk/etc/apps/TA-nextdns-api"

